### ISSUE TITLE
feat: hover animation effect on the "Star on GiitHub" and "Contribute Now" buttons

### ISSUE THREAD

**Issue by jayesh2474** [Tanay-ErrorCode/lupo-skill#88]
**Is your feature request related to a problem? Please describe.**
Currently, the "Star on GiitHub" and "Contribute Now" buttons on GitHub do not have any hover animation effects, which can make the user interaction less engaging and visually appealing.

**Describe the solution you'd like**
I would like to add a hover animation effect to the "Star on GiitHub" and "Contribute Now" buttons. This could include a slight color change, scaling effect, or shadow effect to indicate that the button is interactive and enhance the user experience.

**Describe alternatives you've considered**
- Simply changing the color of the button on hover.
- Adding a shadow effect on hover to create a 3D impression.
- Implementing a scaling effect to make the button slightly larger when hovered over.

**Additional context**
Adding these animations can improve the visual feedback for users and make the interface feel more dynamic. Here is a simple example of a possible CSS implementation for the hover effect:

```css
.button-star, .button-contribute {
    transition: transform 0.2s, box-shadow 0.2s;
}

.button-star:hover, .button-contribute:hover {
    transform: scale(1.05);
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
}
```

Adding this feature could enhance the overall user experience on GitHub by making these interactive elements more noticeable and engaging.
